"""empty message

Revision ID: a9d11a559718
Revises: c015cc978704
Create Date: 2025-11-29 21:37:40.253575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9d11a559718'
down_revision: Union[str, None] = 'c015cc978704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivering_info')
    op.add_column('products', sa.Column('kilocalorie', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'kilocalorie')
    op.create_table('delivering_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('house_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entrance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('apartment_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_leave_at_door', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='delivering_info_pkey')
    )
    # ### end Alembic commands ###
