"""fix_primary_key_in_categories

Revision ID: c015cc978704
Revises: 
Create Date: 2025-11-09 16:21:34.422349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c015cc978704'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Удаляем существующий первичный ключ
    op.drop_constraint('categories_pkey', 'categories', type_='primary')

    # 2. Удаляем столбец uuid
    op.drop_column('categories', 'uuid')

    # 3. Создаем новый первичный ключ только на id
    op.create_primary_key('categories_pkey', 'categories', ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Удаляем первичный ключ на id
    op.drop_constraint('categories_pkey', 'categories', type_='primary')

    # 2. Добавляем обратно столбец uuid
    op.add_column('categories', sa.Column('uuid', sa.UUID(), nullable=False))

    # 3. Восстанавливаем составной первичный ключ
    op.create_primary_key('categories_pkey', 'categories', ['id', 'uuid'])

    # ### end Alembic commands ###